Reorder initial checks and resolves #4 by improving error message.

diff --git a/proxpn b/proxpn
--- a/proxpn
+++ b/proxpn
@@ -16,21 +16,50 @@
 # dry-run mode.
 
 echo -e "\nWelcome to the ProXPN OpenVPN Bash Client!"
+echo
 
+OPENVPN=`which openvpn`
+if $OPENVPN > /dev/null; then
+  echo -e "\nOpenVPN not found! It must be installed before proceeding\n"
+  exit 1
+fi
+
+# The recommendation is to write the ovpn file and other configuration
+# information to /etc/proxpn/
+CONF_BASE_PATH=/etc/proxpn/
+CONF_FILE=proxpn.ovpn
+
+# Ensure that the CONF_FILE exists
+declare OPENVPN_CONF
+if [ -e "$CONF_BASE_PATH$CONF_FILE" ]; then
+    OPENVPN_CONF=$CONF_BASE_PATH$CONF_FILE
+else
+    echo "ERROR: No OpenVPN configuration file found at $CONF_BASE_PATH$CONF_FILE!"
+    exit 1
+fi
+
+# By default the user will be prompted for their ProXPN username and password by
+# OpenVPN. To avoid being prompted, an auth file containing two lines with the username
+# on the first line and the password on the second line can be created. The
+# recommendation is to call this file login.conf and store it in $CONF_BASE_PATH.
+# If this file is not found, it will not be used and the user will be prompted
+# for login credentials.
+CREDS_FILE=login.conf
+
+declare AUTH_CREDS
+if [ -e "$CONF_BASE_PATH$CREDS_FILE" ]; then
+    AUTH_CREDS=$CONF_BASE_PATH$CREDS_FILE
+else
+    echo "No credentials file found, you will be prompted by OpenVPN to login to ProXPN"
+fi
 
 # By default automatically connect to ProXPN when running this script
 dryRun=false
 
 if [ $EUID -ne 0 ]; then
    echo "This script must be run as root in order to successfully apply network route configuration."
-   echo -e "Elevated permissions not detected, falling back to dry-run mode..."
+   echo "Elevated permissions not detected, falling back to dry-run mode..."
    dryRun=true
-fi
-
-OPENVPN=`which openvpn`
-if $OPENVPN > /dev/null; then
-  echo -e "\nOpenVPN not found! It must be installed before proceeding\n"
-  exit 1
 fi
 
 # If the user does not want to automatically connect to ProXPN they can pass -dry-run
@@ -54,35 +83,6 @@ function ctrl_c() {
     echo -e "\nProXPN OpenVPN Bash Client has been force quit. Goodbye.\n"
     exit 1
 }
-
-# The recommendation is to write the ovpn file and other configuration
-# information to /etc/proxpn/
-CONF_BASE_PATH=/etc/proxpn/
-CONF_FILE=proxpn.ovpn
-
-# Ensure that the CONF_FILE exists
-declare OPENVPN_CONF
-if [ -e "$CONF_BASE_PATH$CONF_FILE" ]; then
-    OPENVPN_CONF=$CONF_BASE_PATH$CONF_FILE
-else
-    echo -e "ERROR: No OpenVPN configuration file found at !"
-    exit 1
-fi
-
-# By default the user will be prompted for their ProXPN username and password by
-# OpenVPN. To avoid being prompted, an auth file containing two lines with the username
-# on the first line and the password on the second line can be created. The
-# recommendation is to call this file login.conf and store it in $CONF_BASE_PATH.
-# If this file is not found, it will not be used and the user will be prompted
-# for login credentials.
-CREDS_FILE=login.conf
-
-declare AUTH_CREDS
-if [ -e "$CONF_BASE_PATH$CREDS_FILE" ]; then
-    AUTH_CREDS=$CONF_BASE_PATH$CREDS_FILE
-else
-    echo -e "No credentials file found, you will be prompted to login to ProXPN"
-fi
 
 PORT=443
 
@@ -111,7 +111,7 @@ EXIT_NODES[BASIC]=bny1.proxpn.com
 
 declare remote
 
-echo -e "Which exit node would you like to use?"
+echo "Which exit node would you like to use?"
 
 PS3="Select an exit node:"
 select EXITNODE in ${!EXIT_NODES[@]};
@@ -119,14 +119,14 @@ do
     if [ ${EXIT_NODES[$EXITNODE]} ]; then
         remote=${EXIT_NODES[$EXITNODE]}
     else
-        echo -e "ERROR: Bad selection!"
+        echo "ERROR: Bad selection!"
         exit 1
     fi
     break
 done
 
 # Store the command we're about to run in a variable and use the auth-nocache option
-# to ensure openvpn doesn't attempt to cache auth information in memory
+# to ensure OpenVPN doesn't attempt to cache auth information in memory
 COMMAND="$OPENVPN --config $OPENVPN_CONF --remote $remote $PORT --auth-user-pass $AUTH_CREDS --auth-nocache"
 
 # If we're in dry-run mode then print the command and exit
@@ -136,5 +136,5 @@ if [ $dryRun = true ]; then
     exit 0
 fi
 
-echo "Running: \n$COMMAND\n"
+echo -e "Running: \n$COMMAND\n"
 $COMMAND
