Build on merged doc updates by revising installation section.
Using the script should now be more obvious, as well as the steps it performs, if the user wants to manually recreate the process themself.
Also added quotes for most paths, fixed some typos, code indentation, message spacing, and other misc changes.

diff --git a/proxpn b/proxpn
--- a/proxpn
+++ b/proxpn
@@ -32,10 +32,10 @@ CONF_FILE=proxpn.ovpn
 # Ensure that the CONF_FILE exists
 declare OPENVPN_CONF
 if [ -e "$CONF_BASE_PATH$CONF_FILE" ]; then
-    OPENVPN_CONF=$CONF_BASE_PATH$CONF_FILE
+  OPENVPN_CONF=$CONF_BASE_PATH$CONF_FILE
 else
-    echo "ERROR: No OpenVPN configuration file found at $CONF_BASE_PATH$CONF_FILE!"
-    exit 1
+  echo "ERROR: No OpenVPN configuration file found at $CONF_BASE_PATH$CONF_FILE!"
+  exit 1
 fi
 
 # By default the user will be prompted for their ProXPN username and password by
@@ -58,32 +58,31 @@ dryRun=false
 dryRunExitCode=0
 
 # Check for flags
-while [[ $# > 0 ]]
-do
-key="$1"
-case $key in
+while [[ $# > 0 ]]; do
+  key="$1"
+  case $key in
     -dry-run|--dry-run)
-    dryRun=true
-    dryRunExitCode=0
-    echo -e "-dry-run mode active, you will not be automatically connected."
+      dryRun=true
+      dryRunExitCode=0
+      echo -e "-dry-run mode active, you will not be automatically connected."
     ;;
     -r|-remote|--remote)
-    shift
-    remoteName=$1
+      shift
+      remoteName=$1
     ;;
     *)
-    echo -e "Unknown option: $key \nUsage: proxpn [-r|-remote|--remote REMOTE_NAME] [--dry-run|-dry-run]\n"
-    exit 1
+      echo -e "Unknown option: $key \nUsage: proxpn [-r|-remote|--remote REMOTE_NAME] [--dry-run|-dry-run]\n"
+      exit 1
     ;;
-esac
-shift # past argument or value
+  esac
+  shift # past argument or value
 done
 
 if [ $EUID != 0 -a $dryRun != true ]; then
-   echo "This script must be run as root in order to successfully apply network route configuration."
-   echo "Elevated permissions not detected, falling back to dry-run mode..."
-   dryRun=true
-   dryRunExitCode=1
+  echo "This script must be run as root in order to successfully apply network route configuration."
+  echo "Elevated permissions not detected, falling back to dry-run mode..."
+  dryRun=true
+  dryRunExitCode=1
 fi
 
 # Catch control-c signals to make sure we don't lose stty echo
@@ -93,9 +92,9 @@ fi
 # if the shell is frozen or otherwise broken.
 trap ctrl_c INT
 function ctrl_c() {
-    stty echo
-    echo -e "\nProXPN OpenVPN Bash Client has been force quit. Goodbye.\n"
-    exit 1
+  stty echo
+  echo -e "\nProXPN OpenVPN Bash Client has been force quit.  Goodbye.\n"
+  exit 1
 }
 
 PORT=443
@@ -126,33 +125,33 @@ EXIT_NODES[BASIC]=bny1.proxpn.com
 # If a remote wasn't set via flag then prompt the user to select
 # an exit node to connect to.
 if [ ! ${remoteName} ]; then
-    echo -e "\nWhich exit node would you like to use?"
-    PS3="Select an exit node:"
-    select EXITNODE in ${!EXIT_NODES[@]};
-    do
-        remoteName=$EXITNODE
-        break
-    done
+  echo -e "\nWhich exit node would you like to use?"
+  PS3="Select an exit node (1-${#EXIT_NODES[@]}): "
+  select EXITNODE in ${!EXIT_NODES[@]};
+  do
+      remoteName=$EXITNODE
+      break
+  done
 fi
 
 # If the provided or selected exit node throw an error
 if [ ${EXIT_NODES[$remoteName]} ]; then
-    remote=${EXIT_NODES[$remoteName]}
+  remote=${EXIT_NODES[$remoteName]}
 else
-    echo "ERROR: Sorry, the remote you're trying to use is not known. Matching for the remote flag value is case sensitive."
-    exit 1
+  echo "ERROR: Sorry, the remote \"$remoteName\" you're trying to use is not known.  Matching for the remote flag value is case sensitive."
+  exit 1
 fi
 
 # Store the command we're about to run in a variable and use the auth-nocache option
 # to ensure OpenVPN doesn't attempt to cache auth information in memory
-COMMAND="$OPENVPN --config $OPENVPN_CONF --remote $remote $PORT --auth-user-pass $AUTH_CREDS --auth-nocache"
+COMMAND="$OPENVPN --config \"$OPENVPN_CONF\" --remote \"$remote\" $PORT --auth-user-pass \"$AUTH_CREDS\" --auth-nocache"
 
 # If we're in dry-run mode then print the command and exit
 if [ $dryRun = true ]; then
-    echo -e "\nDry run complete!"
-    echo -e "Use following OpenVPN command to connect to ProXPN :\n$COMMAND\n"
-    exit $dryRunExitCode
+  echo -e "\nDry run complete!"
+  echo -e "Use following OpenVPN command to connect to ProXPN:\n$COMMAND\n"
+  exit $dryRunExitCode
 fi
 
-echo -e "Running: \n$COMMAND\n"
+echo -e "\nRunning:\n$COMMAND\n"
 $COMMAND
